FORT09.01 - Flashloan Detector - Anomaly Score & Label Update
NethermindEth/forta-starter-kits pull request #20
Opened 2023-01-05 03:30 UTC by RCantu92

2023-01-11 11:30 UTC, Vxatz requested changes
A few simple fixes requested.

2023-01-11 11:30 UTC, Vxatz commented on flashloan-detector/src/agent.js
> +            Label.fromObject(EntityType.Transaction, txEvent.hash, "Flashloan Transaction", 1),
```suggestion
            Label.fromObject({ entityType: EntityType.Address, entity: initiator, label: "Attacker", confidence: 0.9 }),
            Label.fromObject({
              entityType: EntityType.Transaction,
              entity: txEvent.hash,
              label: "Flashloan Transaction",
              confidence: 1,
            }),
```

2023-01-11 11:30 UTC, Vxatz commented on flashloan-detector/src/agent.js
> +            Label.fromObject(EntityType.Transaction, txEvent.hash, "Flashloan Transaction", 1),
```suggestion
            Label.fromObject({ entityType: EntityType.Address, entity: initiator, label: "Attacker", confidence: 0.6 }),
            Label.fromObject({
              entityType: EntityType.Transaction,
              entity: txEvent.hash,
              label: "Flashloan Transaction",
              confidence: 1,
            }),
```

2023-01-11 11:30 UTC, Vxatz commented on flashloan-detector/src/agent.js
> +            Label.fromObject(EntityType.Transaction, txEvent.hash, "Flashloan Transaction", 1),
```suggestion
            Label.fromObject({ entityType: EntityType.Address, entity: initiator, label: "Attacker", confidence: 0.9 }),
            Label.fromObject({
              entityType: EntityType.Transaction,
              entity: txEvent.hash,
              label: "Flashloan Transaction",
              confidence: 1,
            }),
```

2023-01-11 11:30 UTC, Vxatz commented on flashloan-detector/src/agent.js
> +            Label.fromObject(EntityType.Transaction, txEvent.hash, "Flashloan Transaction", 1),
A small fix to the Labels.

(The Labels in the tests need to also be updated)

2023-01-11 11:30 UTC, Vxatz commented on flashloan-detector/src/persistence.helper.spec.js
> +
```suggestion

const { Response } = jest.requireActual("node-fetch");
```

The tests somehow failed without this import when I ran them this time.

2023-01-11 11:30 UTC, Vxatz commented on flashloan-detector/README.md
> +    - Label 01:
Only out of curiosity, could you elaborate on the Label numbers?

2023-01-11 20:43 UTC, RCantu92 commented on flashloan-detector/src/persistence.helper.spec.js
> +
Did you get any specific errors? They are passing locally on my machine when I run them.

2023-01-11 20:45 UTC, RCantu92 commented on flashloan-detector/README.md
> +    - Label 01:
Oh, the numbers were just to distinguish one from the other, since there are two of them.

Though, thinking about it, removing the number could still make sense since the descriptions of each property would still differ. I will remove.

2023-01-12 09:34 UTC, Vxatz commented on flashloan-detector/src/persistence.helper.spec.js
> +
I'm getting a `ReferenceError: Response is not defined` when testing it on a different environment (GH Codespaces), while I don't, using my local machine. When not imported from `node-fetch` it seems that the import comes from the local Typescript module. Can you check the source of the import?

2023-01-12 13:23 UTC, Vxatz commented on flashloan-detector/README.md
> +    - Label 01:
I was mostly curious about the way of the numbering, e.g. the "01" instead of "1" and this being before the "0". 

I think we can keep the numbers, perhaps changing them to "Label 1", "Label 2" etc.

By the way, right now the Labels of one of the alerts have numbers and the other's don't.

2023-01-12 13:36 UTC, Vxatz commented on flashloan-detector/README.md
> +    - Label 01:
Oh, two more things I noticed about the README:
1) `anomalyScore` score should be added to the `metadata`
2) We can use the exact value of the confidence level as it is a constant ("always set to X"), instead of the "(0-1)"

2023-01-12 16:37 UTC, Vxatz approved these changes
LGTM ✅

2023-01-12 19:31 UTC, merged