FORT02.04 Multicall Fix for Optimism
NethermindEth/forta-starter-kits pull request #36
Opened 2023-02-28 12:18 UTC by 0xtaf

This fix removes `ethers-multicall` package and replaces it with the Multicall utils in `forta-agent-tools` and enables calls for Optimism chain.

2023-02-28 17:17 UTC, Vxatz requested changes
1) in the `calculateBorrowedAmount` function in helper.js, can you change the order of checking the `!response.data[asset]` and setting the `usdPrice`. (The correct order is the one in the `calculateNativeUsdProfit`.

2) The package version needs to be increased

2023-02-28 17:17 UTC, Vxatz commented on flashloan-detector/src/helper.js
> +        return;
I think it makes more sense to return `0` here

2023-02-28 17:17 UTC, Vxatz commented on flashloan-detector/src/helper.js
> +        return;
Similarly, here maybe it's better to return max uint

2023-02-28 17:37 UTC, Vxatz commented
One more thing, can you add retries to the 3 calls to CoinGecko? I think this help in fixing more errors
You could add 2 max retries and set a timeout of 500ms between each one

2023-03-01 07:06 UTC, 0xtaf commented
made some substantial changes with the coingecko calls

2023-03-01 13:05 UTC, Vxatz approved these changes
Approved ✅

2023-03-01 13:13 UTC, merged